name: Build Executables

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Executable
      run: |
        pyinstaller --onefile --icon=logo.ico main.py

    - name: Rename Executable
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          mv dist/main.exe dv78.exe
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          mv dist/main dv78_macos
        else
          mv dist/main dv78_linux
        fi

    - name: Upload Executables
      uses: actions/upload-artifact@v2
      with:
        name: dv78-executables-${{ matrix.os }}
        path: dv78.*
